/**
 * Lightweight AI provider abstraction.
 *
 * The AI workspace is fully functional today using deterministic heuristics.
 * When `OPENAI_API_KEY` is configured the same calls are enriched with a
 * natural-language narrative generated by OpenAI. We call the REST API with
 * `fetch` so no extra dependency is required ("connect OpenAI later").
 */

export function isAiConfigured() {
  return Boolean(process.env.OPENAI_API_KEY);
}

const OPENAI_MODEL = process.env.OPENAI_MODEL ?? "gpt-4o-mini";

/**
 * Ask the model for a short narrative given a system role and a JSON context.
 * Returns `null` when no key is configured or the call fails, so callers can
 * always fall back to their heuristic output.
 */
export async function generateNarrative(input: {
  system: string;
  context: unknown;
  maxWords?: number;
}): Promise<string | null> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return null;
  }

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: OPENAI_MODEL,
        temperature: 0.4,
        messages: [
          {
            role: "system",
            content: `${input.system} Respond in at most ${input.maxWords ?? 90} words. Be concrete and reference the data.`
          },
          { role: "user", content: JSON.stringify(input.context) }
        ]
      })
    });

    if (!response.ok) {
      return null;
    }

    const data = (await response.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    return data.choices?.[0]?.message?.content?.trim() ?? null;
  } catch {
    return null;
  }
}
